name: Continuous Integration
run-name: ${{ github.actor }} is testing out GitHub Actions [ Event ${{ github.event_name }} ]

on:
  # Triggers the workflow on push and pull request events but only for the "main" branch
  push:
    branches: [ main, develop ]
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main, develop ]
    
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
   build:
    # The type of runner that the job will run on (Selecting Ubuntu as the operating system)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # Display event information
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          
      # Clone the repository
      - name: Check out repository code
        uses: actions/checkout@v3  
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      # Display repository information
      - name: Display repository information
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"
          echo "----------------------"
          echo "List files in the repository:"
          ls -a ${{ github.workspace }}
          echo "----------------------"
      
      # Specify the Node.js version
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      # Download project dependencies
      - name: Install dependencies
        run: npm install
           
      # Execute the build script
      - name: Build project
        run: npm run build

      # Execute unit tests
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: Run unit tests
        run: npm test

      - run: echo "This job's status is ${{ job.status }}."
      
