name: SonarCloud Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ "main" ]
    
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sonarqube-analysis:
    name: SonarCloud Analysis 
    runs-on: ubuntu-latest

    steps:
      # Clone the repository
      - name: Checkout repository code
        uses: actions/checkout@v3  
        with:
          fetch-depth: 0   # Disabling shallow clone is recommended for improving relevancy of reporting
 
      # Setup Node.js
      #- name: Set up Node.js 20
      #  uses: actions/setup-node@v3
      #  with:
      #    node-version: '20'
      #    cache: 'npm'

      # Download project dependencies
      #- name: Node install dependencies
      #  run: npm ci

      # Execute unit tests
      #- name: Run Unit Tests
      #  run: npm test

      #- name: Cache SonarQube packages
      #  uses: actions/cache@v1
      #  with:
      #    path: ~/.sonar/cache
      #    key: ${{ runner.os }}-sonar
      #    restore-keys: ${{ runner.os }}-sonar
          
      #- name: SonarQube Scan
      #  uses: sonarsource/sonarqube-scan-action@master
      #  env:
      #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}